### ISSUE TITLE
Error when instantiating VfxManager

### ISSUE THREAD

**Issue by hdescottes** [crashinvaders/gdx-vfx#15]
It seems like VfxManager is not working anymore with the release 1.9.14 of libGDX.

`vfxManager = new VfxManager(Pixmap.Format.RGBA8888); `

is leading to :

> Exception in thread "LWJGL Application" org.lwjgl.opengl.OpenGLException: Cannot use offsets when Pixel Unpack Buffer Object is disabled
	at org.lwjgl.opengl.GLChecks.ensureUnpackPBOenabled(GLChecks.java:125)
	at org.lwjgl.opengl.GL11.glTexImage2D(GL11.java:2899)
	at com.badlogic.gdx.backends.lwjgl.LwjglGL20.glTexImage2D(LwjglGL20.java:598)
	at com.badlogic.gdx.graphics.glutils.GLOnlyTextureData.consumeCustomData(GLOnlyTextureData.java:78)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:270)
	at com.badlogic.gdx.graphics.GLTexture.uploadImageData(GLTexture.java:257)
	at com.badlogic.gdx.graphics.Texture.load(Texture.java:159)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:147)
	at com.badlogic.gdx.graphics.Texture.<init>(Texture.java:142)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.createTexture(FrameBuffer.java:81)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.createTexture(FrameBuffer.java:42)
	at com.badlogic.gdx.graphics.glutils.GLFrameBuffer.build(GLFrameBuffer.java:174)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:75)
	at com.badlogic.gdx.graphics.glutils.FrameBuffer.<init>(FrameBuffer.java:57)
	at com.crashinvaders.vfx.framebuffer.VfxFrameBuffer.initialize(VfxFrameBuffer.java:107)
	at com.crashinvaders.vfx.framebuffer.VfxFrameBufferPool.createBuffer(VfxFrameBufferPool.java:134)
	at com.crashinvaders.vfx.framebuffer.VfxFrameBufferPool.obtain(VfxFrameBufferPool.java:94)
	at com.crashinvaders.vfx.framebuffer.VfxPingPongWrapper.initialize(VfxPingPongWrapper.java:74)
	at com.crashinvaders.vfx.framebuffer.VfxPingPongWrapper.<init>(VfxPingPongWrapper.java:65)
	at com.crashinvaders.vfx.VfxManager.<init>(VfxManager.java:67)
	at com.crashinvaders.vfx.VfxManager.<init>(VfxManager.java:57)

**Comment by mgsx-dev** [comment]
@hdescottes this is a regression in libGDX 1.9.14, see https://github.com/libgdx/libgdx/issues/6407. either downgrade to 1.9.13 or use 1.9.15-SNAPSHOT.
@metaphore this is not an issue with your library.

**Comment by hdescottes** [comment]
my bad.
Thanks

**Comment by metaphore** [comment]
@mgsx-dev thanks for checking on the issue!
