### ISSUE TITLE
crashes on macos m1 when using opengl 3.2

### ISSUE THREAD

**Issue by abdallabushnaq** [crashinvaders/gdx-vfx#18]
```
java.lang.IllegalStateException: An attempted fetch uniform from uncompiled shader 
Vertex shader
ERROR: 0:9: 'attribute' : syntax error: syntax error
Fragment shader:
ERROR: 0:9: 'varying' : syntax error: syntax error

	at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:304)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.fetchUniformLocation(ShaderProgram.java:293)
	at com.badlogic.gdx.graphics.glutils.ShaderProgram.setUniformi(ShaderProgram.java:318)
	at com.crashinvaders.vfx.framebuffer.VfxFrameBufferRenderer.rebind(VfxFrameBufferRenderer.java:77)
	at com.crashinvaders.vfx.framebuffer.VfxFrameBufferRenderer.<init>(VfxFrameBufferRenderer.java:66)
	at com.crashinvaders.vfx.VfxRenderContext.<init>(VfxRenderContext.java:37)
	at com.crashinvaders.vfx.VfxManager.<init>(VfxManager.java:64)
	at com.crashinvaders.vfx.VfxManager.<init>(VfxManager.java:57)
```

macos implementation is not backward compatible.

I will update this ticket when I get it working.
As I am currently not working with fbos, because they do not support sampling, I am removing vfx for now from my project.

**Comment by abdallabushnaq** [comment]
As I am not using vfx until libgdx supports multi sample fbos, I am closing this issue, as I cannot help fixing it.
